### ISSUE TITLE
How to use the pre-trained or fine-tuned model for high-frequency and long-term data?

### ISSUE THREAD

**Issue by XiaoqZhang** [amazon-science/chronos-forecasting#108]
Hello, I am interested in using this model for predicting high-frequency (1s) and long-term (1e6 to 5e7 s) data. I fine-tuned the `chronos-t5-mini` model with the configuration below:
```
training_data_paths:
- "<path_to_my_arrow_file>"
probability:
- 1.0
context_length: 512
prediction_length: 64
min_past: 60
max_steps: 200_000
save_steps: 100_000
log_steps: 500
per_device_train_batch_size: 32
learning_rate: 0.001
optim: adamw_torch_fused
num_samples: 20
shuffle_buffer_length: 100_000
gradient_accumulation_steps: 1
model_id: google/t5-efficient-mini
model_type: seq2seq
random_init: true
tie_embeddings: true
output_dir: ./output/
tf32: true
torch_compile: true
tokenizer_class: "MeanScaleUniformBins"
tokenizer_kwargs:
  low_limit: -15.0
  high_limit: 15.0
n_tokens: 4096
lr_scheduler_type: linear
warmup_ratio: 0.0
dataloader_num_workers: 1
max_missing_prop: 0.9
use_eos_token: true
```
As the model is suggested to predict 64 timesteps at most every time, I made the model predict 64 steps and then used the predictions as context and asked for the next 64 predictions. I found that the predictions performed quite well in the first 6 rounds. Since the 7th round, the amplitude of the predictions dropped largely and the predictions converged to 0 as the plot shown below. Even though the model can perform quite well until around 1000 steps, which is far from the length that I need, I would like to ask if you have tested any case like this or do you have any suggestions? I have thought about fine-tuning the model with large context and prediction length. But it cannot solve the fundamental problem due to the limitation of the GPU memory. 

![image](https://github.com/amazon-science/chronos-forecasting/assets/90387077/ffc39ed9-95f1-4087-9122-8210d5dd9e5d)
